### ISSUE TITLE
Create manifests for OpenSUSE

### ISSUE THREAD

**Issue by inercia** [kubic-project/terraform#42]
We are currently processing in `provision-dashboard.sh` the manifests files installed in CaaSP. However, these manifests

1. are only installed in CaaSP (ie, the `caasp-container-manifests.rpm` is not available for OpenSUSE)
2. they use images based on SLE

We should support OpenSUSE, and that means that we should

* get those manifests installed in `/usr/share/caasp-container-manifests` somehow
    * we want to use https://github.com/kubic-project/caasp-container-manifests as the only
    source of truth for these manifests, so we don't want to keep a copy in this repo
* replace paths (as we currently do) in the `provision-dashboard.sh`, but also some images names by the OpenSUSE equivalents.

**Comment by PI-Victor** [comment]
as @inercia said, it might prove to be difficult. @mjura i didn't think this would be challenging enough for two persons to work on it, but if you have any issues and there's anything i can do to help, let me know, i'd be happy to.
