### ISSUE TITLE
Terraform error running on Tumbleweed

### ISSUE THREAD

**Issue by robdaemon** [kubic-project/terraform#55]
I'm getting an error running this from on Tumbleweed as of 28-Apr:

```
Error asking for user input: 1 error(s) occurred:

* provider.libvirt: Incompatible API version with plugin. Plugin version: 2, Ours: 4
```

Terraform and the plugin come from this repo: http://download.opensuse.org/repositories/Virtualization:/containers/openSUSE_Tumbleweed/

terraform package version 0.9.4-1.1
terraform-provider-libvirt package version 0.0.0+git20170315.6863033-1.5

**Comment by inercia** [comment]
That is because of an incompatibility between the Terraform API and the plugin. As a workaround, you could install both things from the source code...
